language: generic

sudo: required

services: 
  - docker

before_install:
  - docker build -t prashanth1261/dockerreact -f dockerfile.dev .

script:
  - docker run -e CI=true prashanth1261/dockerreact npm run test -- --coverage