language: generic

sudo: required

services: 
  - docker

before_install:
  - docker build -t prashanth1261/dockerreact -f dockerfile.dev .

script:
  - docker run -e CI=true prashanth1261/dockerreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-848819479142"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
